### ISSUE TITLE
 Make search bar big and add hover effect in it, which matches with the theme of website.

### ISSUE THREAD

**Issue by SumanLeetcoder** [SumanLeetcoder/Personal-Project#1]
Please attach me ss of before and after while you try for PR.

**Comment by siddhant7666** [comment]
Hello @SumanLeetcoder can you please assign this issue to me, as I can do this within a day, and please add hacktoberfest and hacktoberfest-accepted label to it.

**Comment by SumanLeetcoder** [comment]
Done, will add label after you have resolved the issue.

**Comment by siddhant7666** [comment]
Done, please accept my PR and sugggest me if some changes are needed.

**Comment by SumanLeetcoder** [comment]
I think its looking fine. Thanks
